### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by pizzamaker** [christarazi/random-restaurant-generator#1]
Play Services is non-free software, could you provide a gradle flavor that does not require this?

This is needed for inclusion on F-Droid.

**Comment by christarazi** [comment]
Do you know of any floss libraries that are alternatives to Google Play Services?

**Comment by pizzamaker** [comment]
It depends, what are you using play services for?

**Comment by christarazi** [comment]
I'm using Google Maps to display where the restaurant is, as well as calculating the distance from the restaurant to the user. 

For example, if the user elects to not use their GPS, they must enter a location. Let's say they pick San Francisco, CA. So when they generate a restaurant, I use Google Maps API to calculate the distance from the restaurant to the city (or zip code, etc.) that the user is in. See screenshot below. 

![screenshot_2016-01-24-16-24-15](https://cloud.githubusercontent.com/assets/3885308/12591287/e8abd060-c41b-11e5-8a11-d76448275214.png)

**Comment by pizzamaker** [comment]
Have you looked into OpenStreetMap's API? https://wiki.openstreetmap.org/wiki/API

**Comment by christarazi** [comment]
I'll look into it. Hopefully there's an Android API for it.

**Comment by christarazi** [comment]
@pizzamaker Sorry for the long delay. Unfortunately I do not think it is feasible for me to support two separate version of this app. I wish I can but I simply do not have the time.

**Comment by pizzamaker** [comment]
Just as a last-resource suggestion, I'd encourage you to look into the https://github.com/microg project :)
