### ISSUE TITLE
App doesn't ask for location permission

### ISSUE THREAD

**Issue by variadico** [christarazi/random-restaurant-generator#2]
**Issue**
Pressing GPS button didn't ask me to grant permission to find my location by using GPS.

**Reproduce**
1. Download app from Play store.
2. Open app and click the GPS button.

**Expected Behavior**
The app should have displayed a permission dialog to grant permissions.

**Actual Behavior**
The app displays a Toast that says "Location permission currently denied". I had to manually go into my system preferences and give the app permission from there.

**Device**
Nexus 5X with Android 6.0.1.

**Comment by christarazi** [comment]
Did you disable Location permissions by default? As in, did you manually go in and disable it? 

I believe the way the Android Marshmallow permission system works is that if you disable any permission manually, an app does not have the capability to revert it, unless you manually go back and enabled it. At least that was my experience. 

Thanks for submitting this by the way.

**Comment by christarazi** [comment]
@variadico Sorry for the long delay, but I released a new update today. It's been tough to find time, but the location permissions issues should be fixed now. Let me know your thoughts.
